mybatis:
  type-aliases-package: com.example.entity,com.example.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  before: true
  safe-delete: true
  safe-update: true
pagehelper:
  offset-as-page-num: true
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2000
      pool-name: hikariCP
      connection-timeout: 10000
  redis:
    timeout: 1s
    jedis:
      pool:
        max-idle: 100
        min-idle: 50
        max-active: 1000
dubbo:
  application:
    name: dubbo-template
  protocol:
    name: dubbo
    port: 20887
  provider:
    timeout: 10000
  registry:
    address: nacos://127.0.0.1:8848